server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            client-name: Google
        provider: # this is optional because Spring Boot and Security know about Google
          google:
            issuer-uri: https://accounts.google.com